config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: {
        registrations: 'users/registrations'
	} 

	root to: 'pages#index'

	resources :menus
	get 'cooks/:id/menu_show', to: 'cooks#menu_show', as:'menu_show'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord
 belongs_to :user
 has_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
  mount_uploader :picture, ImageMenuUploader
  belongs_to :cook
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :menu
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :picture, AvatarUploader
  has_many :cooks

  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
	  
	  def menu_show
	  	@cook = Cook.find(params[:id])
	  	@menus = @cook.menus
	  end

	private
	 	def menu_params
	 		params.require(:cook).permit(:name, :description, :picture, :price, :cook_id, :date)
	 	end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!
  before_action :set_menu, only: [:show, :edit, :update, :destroy]
  before_action :set_menus, only: [:index, :new, :edit]
  before_action :set_cook, only: [:new, :edit]
  # GET /menus
  # GET /menus.json
  def index
    ##chequear si el usuario es cocinero
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)
    @menu.cook_id = current_user.id
    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    @menu.remove_picture!
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    def set_menus
      @menus = Menu.where("cook_id=#{current_user.id}")
    end
    def set_cook
      @cook = Cook.where("user_id=#{current_user.id}")
    end  
    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:name, :description, :picture, :price, :date)
    end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	    @cooks = Cook.all
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :picture, :phone])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cooks/index.html.erb
<!-- menú de navegación -->
<%= render 'shared/navbar' %>

<section class="slider">
  <!-- Jumbotron -->
  <div class="jumbotron mt-5 rounded-0 bg-transparent">
    <div class="container">
      <h1 class="display-3">Hello, world!</h1>
      <p class="lead text-white">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p class="text-white">It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p>
    </div>
  </div>
  <!-- Fin Jumbotron -->
</section>

<!-- Cards -->
<section class="container mt-5">
  <div class="row">
    <% @cooks.each do |cook| %>
    <div class="col-md-4">
      <div class="card mt-3">
        <%= image_tag cook.picture, class: 'card-img-top img-fluid' %>
        <div class="card-body">
          <h4 class="card-title"><%= cook.name%></h4>
          <p class="card-text"><%= cook.biography %></p>
          <p> <%= cook.address_commune %></p>
          <p> <%= cook.address_region %></p>
        </div>
        <div class="card-footer d-flex flex-row justify-content-center">
          <%= link_to("ver Menu", list_menu_path(cook), class:"btn btn-outline-primary mr-2" ) %>
          <%= link_to("Crear Menu", cook_path(cook), class:"btn btn-outline-primary" ) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>
<!-- Fin Cards -->

app/views/cooks/menu_show.html.erb
<!-- menú de navegación -->
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>
<h1 class="jumbotron"><%= @cook.name %></h1>
	<div class="row">
		<div class="col">
			<section class="cook">
				<%= image_tag @cook.picture, size:"32X32", class: 'card-img-top img-fluid' %>
				<div class="card cook">
				  <div class="card-body">
				    <h4 class="card-title"><%= @cook.name%></h4>
				    <p class="card-text"><%= @cook.biography %></p>
				    <p> <%= @cook.address_commune %></p>
				    <p> <%= @cook.address_region %></p>
				  </div>
			</section>
		</div>
		<div class="col">
				<section class="menus">
					<div class="row">
						<%= @menus.each_slice(2) do |row|  %>
							<% row.each do |menu| %>
								<div class="col">
									<div class="card-deck"">
										<div class="card">
											<%= image_tag menu.picture.thumb, class: 'card-img-top img-fluid' %>
											<div class="card-body">
											<h5><%= menu.name %></h5>
											<p><%= "$ " + menu.price.to_s %><p>
											<p class="card-text"><%= menu.description %></p>
											<%= link_to "Reservar",  root_path , class: "btn btn-success" %>
										</div>
									</div>
								</div>
							</div>
						<% end %>
					<div class="w-100" style="margin-top: 20px"></div>
					<% end %>
					</div>
				</section>
		</div>
	</div>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>

  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Nombre de cocinero: <%= @cook.name %></h3>
  <h3> Menus:</h3>
  <ul>
    <% @menus.each do |menu| %>
      <li>
        <%= menu.name %>
      </li>
    <% end %>
  </ul>  



  <div class="field">
    <%= form.label :name, "Nombre del plato" %>
    <%= form.text_field :name, id: :menu_name %>
  </div>

  <div class="field">
    <%= form.label :description, "Cuentanos detalles de tu Plato" %>
    <%= form.text_area :description, id: :menu_description %>
  </div>

  <div class="field">
    <%= form.label :picture, "Pudes poner su foto" %>
    <%= form.file_field :picture, id: :menu_picture %>
  </div>

  <div class="field">
    <%= form.label :price, "Precio del Plato" %>
    <%= form.number_field :price, id: :menu_price %>
  </div>

  <div class="field">
    <%= form.label :date, "Fecha de Venta" %>
    <%= form.date_select :date, id: :menu_date %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th>Cooks</th>
      <th>Date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.name %></td>
        <td><%= menu.description %></td>
        <td>
          <a href="<%= menu_path(menu) %>">
            <%= image_tag menu.picture.thumb ,class:"menu-img" %>
          </a>
        </td>
        <td><%= menu.price %></td>
        <td><%= menu.cook.name %></td>
        <td><%= menu.date %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %> <br>

<%= link_to 'Home', root_path%> 

app/views/menus/new.html.erb
<h1>Crea tus Platos</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @menu.picture %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<p>
  <strong>Cooks:</strong>
  <%= @menu.cook %>
</p>

<p>
  <strong>Date:</strong>
  <%= @menu.date %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/pages/index.html.erb
<!-- menú de navegación -->
<%= render 'shared/navbar' %>

<section class="slider">
  <!-- Jumbotron -->
  <div class="jumbotron mt-5 rounded-0 bg-transparent">
    <div class="container">
      <h1 class="display-3">Hello, world!</h1>
      <p class="lead text-white">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p class="text-white">It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p>
    </div>
  </div>
  <!-- Fin Jumbotron -->
</section>

<!-- Cards -->
<section class="container mt-5">
  <div class="row">
    <% @cooks.each do |cook| %>
    <div class="col-md-4">
      <div class="card mt-3">
        <%= image_tag cook.picture, class: 'card-img-top img-fluid' %>
        <div class="card-body">
          <h4 class="card-title"><%= cook.name%></h4>
          <p class="card-text"><%= cook.biography %></p>
          <p> <%= cook.address_commune %></p>
          <p> <%= cook.address_region %></p>
        </div>
        <div class="card-footer d-flex flex-row justify-content-center">
          <%= link_to("ver Menu", menu_show_path(cook), class:"btn btn-outline-primary mr-2" ) %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</section>
<!-- Fin Cards -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag "logo-02.svg", with: "30", height: "30", class: "d-inline-block align-top" %>
    La tía.cl!
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <div class="navbar-nav mr-auto ml-auto text-center">
      <a class="nav-item nav-link active" href="#">Home</a>
      <a class="nav-item nav-link" href="#">Nosotros</a>
      <a class="nav-item nav-link" href="#">Servicio</a>
      <a class="nav-item nav-link" href="#">Contacto</a>
    </div>

    <% if user_signed_in? %>

    <div class="d-flex flex-row justify-content-center">
        <a href="#" class="nav-item nav-link text-white">Bienvenido</a>
    
        <%= image_tag current_user.picture.thumb, class: "d-inline-block align-top avatar" %>


        <div class="d-flex flex-row justify-content-center">
        <a href="#" class="nav-item nav-link text-white"><%= current_user.name %></a>

        <% if current_user.cook == true %>
          <a class="nav-item nav-link text-white" href="<%= menus_path %>">Crea Tus Platos</a>
        <% end %>
        
        <a href="<%= destroy_user_session_path %>" data-method="DELETE" class="btn btn-outline-primary text-white border-white mr-2">Salir</a>

    </div>

    <% else %>
    <div class="d-flex flex-row justify-content-center">
      <a href="<%= new_user_session_path %>" class="btn btn-outline-primary text-white border-white mr-2">Ingresar</a>
      <a href="<%= new_user_registration_path %>" class="btn btn-outline-primary text-white border-white">Registrarse</a>
    </div>
    <% end %>
  </div>
</nav>
<!-- Fin menú de navegación -->